### PR TITLE
Fix #67: make ng-joyride work with jQuery v3.0. Add LICENSE file.

### LINKED ISSUE #67: joyride not working with jQuery3
I just noticed, that ng-joyride is not working with jQuery3 yet, I tried for hours to get it working until I figured out the error. In ng-joyride.js, line 473 you write "if ($fkEl.size() === 0) {", but size() is deprecated since jQuery 1.8, and it v3 it doesn't seem to work at all any more. If changing .size() to the attribute .length it works fine, but I'm now using jQuery 2.2.4, where it's working without changing anything as well. 

Please fix that for the next version (so change .size() to .length), so it works with jQuery3 as well.

### PR DESCRIPTION
**Pull request by seanlip**

### CODE REVIEW

**Comment by Deklin** [comment]
@seanlip any chance of fixing the conflicts so this can be merged?

**Comment by seanlip** [comment]
Hi @deklin -- I'd be happy to, but I'm not sure the author is still maintaining the repo. I sent this PR in almost a year ago, and emailed the author, but never got any response...

**Comment by Deklin** [comment]
I created a PR as well. I may switch to angular-joyride but will need to update that to support jquery style selectors. This one handled conditionals better for responsive layouts so I could use :hidden and :visible selectors. 

I wonder if this is still being maintained

**Comment by abhikmitra** [comment]
Sorry guys . I have been extremely busy !. But I did merge your PR. 

Thanks a lot for helping me out !

**Comment by abhikmitra** [comment]
@seanlip Can you fix the conflicts ?

**Comment by seanlip** [comment]
Thanks @abhikmitra! Sure, I'll try and take a look tonight when I get back from work.

**Comment by seanlip** [comment]
OK -- I did take a quick look at this, but there are indeed merge conflicts, and resolving them correctly without breaking things will require more investigation than I have time for at the moment, I'm afraid.

So, I'm going to close this PR. However, @Deklin @abhikmitra: if you'd like to make further changes to the library based on the ones in this PR, please feel free to do so. Thanks!

**Comment by Deklin** [comment]
@seanlip I have opened a PR relating to your PR.
https://github.com/abhikmitra/ng-joyride/pull/80
Which was subsequently merged.

**Pull request closed without merging**
