### PR TITLE
joyrideTitle button text as config parameter (already existing stored…

### PR DESCRIPTION
**Pull request by Hazarapet**
button texts are config parameters.I need to show another texts.already existing texts are used as by default

### CODE REVIEW

**Comment by abhikmitra** [comment]
Looks good. Can u remove workspace.xml changes ( i need to remove it here also ) and include some updates in the documentation

**Comment by Hazarapet** [comment]
I wondered why haven't you put .idea directory in .gitignore file. That's not useful.you can remove it and put into git ignore

**Comment by Hazarapet** [comment]
by the way I've changed only for "title" type.maybe will be good to change for all types. (I just needed to change only for title types)

**Comment by abhikmitra** [comment]
Thats ok . You can just add the new configuration in the title step part of the documentation.

**Comment by Hazarapet** [comment]
Should I make new pull request for both (remove this), or only just for documentation

**Pull request merged**
